import '../config/firebase_config.dart';

/// Generates build.yaml template from Firebase configs
class BuildYamlTemplate {
  /// Generate build.yaml content from Firebase configs
  static String generate({
    required List<FirebaseConfig> configs,
    String? projectName,
    String? projectVersion,
  }) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('# Firebase App Distribution Build Configuration');
    buffer.writeln('# Auto-generated by pipo_firebase_app_distribution');
    buffer.writeln('# https://pub.dev/packages/pipo_firebase_app_distribution');
    buffer.writeln();
    buffer.writeln('# Authentication:');
    buffer.writeln('# Place your Google Cloud service account JSON key file as');
    buffer.writeln('# .firebase-credentials.json in the project root, or set the');
    buffer.writeln('# credentials_file path under the firebase section below, or set');
    buffer.writeln('# the GOOGLE_APPLICATION_CREDENTIALS environment variable.');
    buffer.writeln('# The credentials file is auto-added to .gitignore.');
    buffer.writeln();

    // Project info
    buffer.writeln('project:');
    buffer.writeln('  name: "${projectName ?? "My App"}"');
    buffer.writeln('  version: "${projectVersion ?? "1.0.0+1"}"');
    buffer.writeln('  use_fvm: false  # Set to true if using FVM (Flutter Version Management)');
    buffer.writeln();

    // Firebase configuration (from first config)
    if (configs.isNotEmpty) {
      final firstConfig = configs.first;
      buffer.writeln('firebase:');
      buffer.writeln('  project_id: "${firstConfig.projectId}"');
      buffer.writeln('  project_number: "${firstConfig.projectNumber}"');
      buffer.writeln('  timeout: 600');
      buffer.writeln('  credentials_file: ".firebase-credentials.json"  # Path to service account JSON key');
      buffer.writeln();
    }

    // Environment configurations
    buffer.writeln('# Environment configurations');
    buffer.writeln('environments:');

    // Group configs by environment
    final envGroups = <String, List<FirebaseConfig>>{};
    for (final config in configs) {
      final env = config.environment ?? 'unknown';
      envGroups.putIfAbsent(env, () => []).add(config);
    }

    // Sort environments: dev, staging, production, others
    final sortedEnvs = envGroups.keys.toList()
      ..sort((a, b) {
        const order = ['dev', 'staging', 'production'];
        final aIndex = order.indexOf(a);
        final bIndex = order.indexOf(b);
        if (aIndex != -1 && bIndex != -1) return aIndex.compareTo(bIndex);
        if (aIndex != -1) return -1;
        if (bIndex != -1) return 1;
        return a.compareTo(b);
      });

    for (final env in sortedEnvs) {
      final envConfigs = envGroups[env]!;
      final androidConfig = envConfigs.firstWhere(
        (c) => c.platform == 'android',
        orElse: () => envConfigs.first,
      );
      final iosConfig = envConfigs.firstWhere(
        (c) => c.platform == 'ios',
        orElse: () => envConfigs.first,
      );

      buffer.writeln('  $env:');

      // Android app ID
      if (androidConfig.platform == 'android') {
        buffer.writeln('    android_app_id: "${androidConfig.appId}"');
        buffer.writeln('    android_bundle_id: "${androidConfig.bundleId}"');
      }

      // iOS app ID
      if (iosConfig.platform == 'ios') {
        buffer.writeln('    ios_app_id: "${iosConfig.appId}"');
        buffer.writeln('    ios_bundle_id: "${iosConfig.bundleId}"');
      }

      // Distribution groups
      final group = _getDefaultGroup(env);
      buffer.writeln('    groups:');
      buffer.writeln('      - "$group"');
      buffer.writeln();

      // Setup configuration
      buffer.writeln('    setup:');
      buffer.writeln('      build_mode: ${_getDefaultBuildMode(env)}');
      buffer.writeln('      upload: ${_getDefaultUpload(env)}');
      buffer.writeln('      obfuscate: ${_getDefaultObfuscate(env)}');
      buffer.writeln('      auto_increment: ${_getDefaultAutoIncrement(env)}');
      buffer.writeln('      clean: true');
      buffer.writeln('      extra_args: []  # Custom flutter build args for both platforms');
      buffer.writeln('      android_extra_args: []  # Android-only args, e.g. ["--split-per-abi"]');
      buffer.writeln('      ios_extra_args: []  # iOS-only args, e.g. ["--export-method ad-hoc"]');
      buffer.writeln();
    }

    // Build presets
    buffer.writeln('# Build presets');
    buffer.writeln('presets:');
    buffer.writeln('  quick-dev:');
    buffer.writeln('    environment: dev');
    buffer.writeln('    build_mode: debug');
    buffer.writeln('    upload: false');
    buffer.writeln('    clean: false');
    buffer.writeln();

    buffer.writeln('  test-build:');
    buffer.writeln('    environment: staging');
    buffer.writeln('    build_mode: release');
    buffer.writeln('    upload: false');
    buffer.writeln('    clean: true');
    buffer.writeln();

    buffer.writeln('  production-release:');
    buffer.writeln('    environment: production');
    buffer.writeln('    build_mode: release');
    buffer.writeln('    upload: true');
    buffer.writeln('    clean: true');
    buffer.writeln('    increment: true');
    buffer.writeln();

    // Default settings
    buffer.writeln('# Default settings');
    buffer.writeln('defaults:');
    buffer.writeln('  build_mode: release');
    buffer.writeln('  upload: true');
    buffer.writeln('  clean: true');
    buffer.writeln('  auto_increment: true');
    buffer.writeln('  obfuscate: false');
    buffer.writeln();

    // Platform-specific settings
    buffer.writeln('# Platform-specific settings');
    buffer.writeln('platforms:');
    buffer.writeln('  android:');
    buffer.writeln('    build_format: apk  # or aab for Play Store');
    buffer.writeln('    flavor_dimension: environment');
    buffer.writeln();
    buffer.writeln('  ios:');
    buffer.writeln('    export_method: development  # or app-store, ad-hoc, enterprise');
    buffer.writeln('    team_id: ""  # Add your Apple Team ID here');

    return buffer.toString();
  }

  /// Get default distribution group based on environment
  static String _getDefaultGroup(String env) {
    switch (env.toLowerCase()) {
      case 'dev':
      case 'development':
        return 'internal-testers';
      case 'staging':
      case 'qa':
        return 'qa-team';
      case 'production':
      case 'prod':
        return 'release-team';
      default:
        return 'internal-testers';
    }
  }

  /// Get default build mode based on environment
  static String _getDefaultBuildMode(String env) {
    switch (env.toLowerCase()) {
      case 'dev':
      case 'development':
        return 'release';
      case 'staging':
      case 'qa':
        return 'release';
      case 'production':
      case 'prod':
        return 'release';
      default:
        return 'release';
    }
  }

  /// Get default upload setting based on environment
  static bool _getDefaultUpload(String env) {
    switch (env.toLowerCase()) {
      case 'dev':
      case 'development':
        return true;
      case 'staging':
      case 'qa':
        return true;
      case 'production':
      case 'prod':
        return true;
      default:
        return false;
    }
  }

  /// Get default obfuscate setting based on environment
  static bool _getDefaultObfuscate(String env) {
    switch (env.toLowerCase()) {
      case 'dev':
      case 'development':
        return false;
      case 'staging':
      case 'qa':
        return false;
      case 'production':
      case 'prod':
        return true;
      default:
        return false;
    }
  }

  /// Get default auto_increment setting based on environment
  static bool _getDefaultAutoIncrement(String env) {
    switch (env.toLowerCase()) {
      case 'dev':
      case 'development':
        return true;
      case 'staging':
      case 'qa':
        return true;
      case 'production':
      case 'prod':
        return false;
      default:
        return true;
    }
  }
}
